### ISSUE TITLE
关于爬取去哪网数据的问题

### ISSUE THREAD

**Issue by SWHL** [pig6/qunar_spider#1]
你好，我对你这个小项目很感兴趣，我一步一步地试了一下，代码没有问题，但是我具体爬取去哪网的数据时，发现我这里和你那里不太一样：
**我的实际截图：**
![me](https://user-images.githubusercontent.com/28639377/66029757-7ffe2b80-e532-11e9-8d26-9737f204a572.jpg)
**你的文中截图：**
![you](https://user-images.githubusercontent.com/28639377/66029803-92786500-e532-11e9-897f-ac6097aa65e6.jpg)

我如果是第一次自己爬，恐怕想不到这样获取数据，对此，你可以具体看一下怎样获取吗？这是我访问的[去哪儿网链接](http://piao.qunar.com/ticket/list.htm?keyword=%E5%9B%BD%E5%BA%86%E6%97%85%E6%B8%B8%E6%99%AF%E7%82%B9&region=&from=mpl_search_suggest)。

非常感谢。

**Comment by Ginnam** [comment]
> 你好，我对你这个小项目很感兴趣，我一步一步地试了一下，代码没有问题，但是我具体爬取去哪网的数据时，发现我这里和你那里不太一样：
> **我的实际截图：**
> ![me](https://user-images.githubusercontent.com/28639377/66029757-7ffe2b80-e532-11e9-8d26-9737f204a572.jpg)
> **你的文中截图：**
> ![you](https://user-images.githubusercontent.com/28639377/66029803-92786500-e532-11e9-897f-ac6097aa65e6.jpg)
> 
> 我如果是第一次自己爬，恐怕想不到这样获取数据，对此，你可以具体看一下怎样获取吗？这是我访问的[去哪儿网链接](http://piao.qunar.com/ticket/list.htm?keyword=%E5%9B%BD%E5%BA%86%E6%97%85%E6%B8%B8%E6%99%AF%E7%82%B9&region=&from=mpl_search_suggest)。
> 
> 非常感谢。

应该是你没有翻页吧

**Comment by SWHL** [comment]
我确定已经翻页了，你那里打开这个[链接](http://piao.qunar.com/ticket/list.htm?keyword=%E5%9B%BD%E5%BA%86%E6%97%85%E6%B8%B8%E6%99%AF%E7%82%B9&region=&from=mpl_search_suggest)，会有你文中那个 **list.json?keyword=** 的文件吗？

**Comment by Ginnam** [comment]
> 我确定已经翻页了，你那里打开这个[链接](http://piao.qunar.com/ticket/list.htm?keyword=%E5%9B%BD%E5%BA%86%E6%97%85%E6%B8%B8%E6%99%AF%E7%82%B9&region=&from=mpl_search_suggest)，会有你文中那个 **list.json?keyword=** 的文件吗？

我不是作者啦.但我的确能找到的
![国庆旅游景点.PNG](https://i.loli.net/2019/10/04/KZ8YqwO4uNga5mL.png)

**Comment by SWHL** [comment]
我知道了，我理解错了翻页的意思，我以为是翻浏览器按F12后的Header那一页呢! 原来是翻景点这一页
谢谢你。
